version: '3.2'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  flask_app:
    image: aniket0808/flask_app:latest
    depends_on:
      - postgres
      - redis
    environment:
      FLASK_ENV: development

  worker:
    image: aniket0808/flask_worker:latest
    depends_on:
      - flask_app
      - redis
      - postgres

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app

volumes:
  postgres_data:
